# Generated by Django 5.2.4 on 2025-07-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemon_description_alter_pokemon_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='jap_eng_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
