# Generated by Django 5.2.4 on 2025-07-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_alter_pokemon_description_alter_pokemon_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='jap_eng_title',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='eng_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Английское имя'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='jap_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Японское имя'),
        ),
    ]
