# Generated by Django 5.2.4 on 2025-07-13 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_remove_pokemon_jap_eng_title_pokemon_eng_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves', to='pokemon_entities.pokemon', verbose_name='Эволюция'),
        ),
    ]
